### ISSUE TITLE
Tracking issue for v1.0 release

### ISSUE THREAD

**Issue by fangyi-zhou** [nuscr/nuscr#47]
Features to complete:
- [x] Names with locations #38 
- [x] Improved error messages #57 #58 
- [x] Curated examples #36 
- [x] Add logo and link to repo in nuscr Live #53

**Comment by fangyi-zhou** [comment]
https://github.com/ocaml/opam-repository/pull/15446
